### ISSUE TITLE
Script phemex_futures_account2_place_trades.sh not place any trades on account2

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/crypto-place-trades#6]
-- hint: bad input variable to app in script

**Comment by LucyQuantAnalyst** [comment]
@GeorgeQuantAnalyst I fixed bug in branch: bugfix/rename_variable_portfolio_to_account_in_phemex_service

and added pull requst
[crypto-place-trades/pull/7](https://github.com/GeorgeQuantAnalyst/crypto-place-trades/pull/7)

**Comment by GeorgeQuantAnalyst** [comment]
Merged into dev branch.
